export const ROLE_CODES = [
  'SUPER_ADMIN','ORG_OWNER','ORG_ADMIN','CEO','CTO','PROJECT_MANAGER','ENGINEERING_MANAGER',
  'TEAM_MANAGER','TEAM_LEAD','DEVELOPER','QA_ENGINEER','DEVOPS_ENGINEER','SECURITY_ENGINEER',
  'COMPLIANCE_REVIEWER','AUDITOR','CLIENT_VIEWER',
] as const;

export type RoleCode = (typeof ROLE_CODES)[number];

export const ADMIN_ROLES: RoleCode[] = ['SUPER_ADMIN', 'ORG_OWNER', 'ORG_ADMIN'];
