import crypto from 'crypto';
import { Errors } from '../api/errors';

// Standard AES-256-GCM configuration
const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 16;
const AUTH_TAG_LENGTH = 16;

/**
 * Returns the 32-byte encryption key configured in the environment.
 * If the key is missing or invalid, throws a fatal error to prevent unencrypted operations.
 */
function getEncryptionKey(): Buffer {
  const keyBase64 = process.env.ENCRYPTION_KEY;
  if (!keyBase64) {
    throw new Error('FATAL: ENCRYPTION_KEY environment variable is not set. Cannot perform cryptographic operations.');
  }
  
  const key = Buffer.from(keyBase64, 'base64');
  if (key.length !== 32) {
    throw new Error(`FATAL: ENCRYPTION_KEY must be exactly 32 bytes (256 bits). Found ${key.length} bytes.`);
  }
  
  return key;
}

/**
 * Encrypts a plaintext string using AES-256-GCM.
 * Returns a colon-separated payload containing: base64(iv):base64(ciphertext):base64(authTag)
 */
export function encrypt(text: string): string {
  const key = getEncryptionKey();
  try {
    const iv = crypto.randomBytes(IV_LENGTH);
    const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
    
    let encrypted = cipher.update(text, 'utf8', 'base64');
    encrypted += cipher.final('base64');
    
    const authTag = cipher.getAuthTag();
    
    // Format: iv:ciphertext:authTag
    return `${iv.toString('base64')}:${encrypted}:${authTag.toString('base64')}`;
  } catch (error: any) {
    console.error('[encryption] Failed to encrypt data:', error.message);
    throw Errors.internal('Failed to encrypt sensitive data.');
  }
}

/**
 * Decrypts a payload generated by `encrypt()`.
 * Accepts a colon-separated payload: base64(iv):base64(ciphertext):base64(authTag)
 */
export function decrypt(encryptedPayload: string): string {
  const key = getEncryptionKey();
  try {
    const parts = encryptedPayload.split(':');
    
    if (parts.length !== 3) {
      throw new Error('Invalid encrypted payload format.');
    }
    
    const [ivBase64, ciphertextBase64, authTagBase64] = parts;
    const iv = Buffer.from(ivBase64, 'base64');
    const authTag = Buffer.from(authTagBase64, 'base64');
    
    const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(authTag);
    
    let decrypted = decipher.update(ciphertextBase64, 'base64', 'utf8');
    decrypted += decipher.final('utf8');
    
    return decrypted;
  } catch (error: any) {
    console.error('[encryption] Failed to decrypt data:', error.message);
    throw Errors.internal('Failed to decrypt sensitive data.');
  }
}
