/**
 * Local dev background worker for scheduled report delivery.
 *
 * Not a full job queue (no Redis/Inngest) — a correct, honest polling loop:
 *  - parses `cron_expression` for real (cron-parser) instead of a hardcoded
 *    "+1 day" next_run_at
 *  - actually generates the report content (CSV) instead of mocking success
 *  - actually attempts email delivery
 *  - uses optimistic-locking claims so two worker instances polling the same
 *    table don't both process (and double-deliver) the same schedule
 *  - records DELIVERED / FAILED honestly in report_deliveries
 *
 * In production this loop would be replaced by a real scheduler (cron /
 * EventBridge / Inngest) and a transactional email provider (Resend /
 * Postmark) — see sendReportEmail() below for the swap point.
 */
const { createClient } = require('@supabase/supabase-js');
const nodemailer = require('nodemailer');
const cronParser = require('cron-parser');
require('dotenv').config({ path: '.env.local' });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
// This project's env uses SUPABASE_SECRET_KEY (see .env.local) rather than
// the more common SUPABASE_SERVICE_ROLE_KEY name; the previous version of
// this script referenced the latter, which meant it silently exited on
// startup in this repo's actual local-dev configuration.
const SUPABASE_SERVICE_ROLE = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE) {
  console.error('Missing Supabase credentials in .env.local');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE);

// While a schedule is being processed we push next_run_at forward by this
// much as part of the claim — acts as both the optimistic-lock marker and a
// crash-recovery TTL (a worker that dies mid-run won't wedge the schedule
// forever; it becomes claimable again after LOCK_TTL_MS).
const LOCK_TTL_MS = 5 * 60 * 1000;

// --- CSV helpers (mirrors lib/csv.ts's escaping so worker-generated CSVs
// match the ones generated by the API routes; duplicated here because this
// script runs under plain `node`, outside the Next.js/TS path-alias build.)
function csvEscape(value) {
  let text = value == null ? '' : String(value);
  // Formula/DDE injection guard — mirrors lib/csv.ts's csvEscape. A cell
  // starting with =, +, -, @, tab, or CR can be interpreted as a formula by
  // Excel/Sheets; prefixing with a leading apostrophe forces plain text.
  if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`;
  if (/[",\r\n]/.test(text)) return `"${text.replaceAll('"', '""')}"`;
  return text;
}
function toCsv(headers, rows) {
  return [
    headers.map(csvEscape).join(','),
    ...rows.map((row) => headers.map((h) => csvEscape(row[h])).join(',')),
  ].join('\r\n');
}

async function generateReportCsv(report) {
  const orgId = report.organization_id;

  if (report.type === 'GLOBAL_ANALYTICS') {
    const [projRes, sprintRes, taskRes] = await Promise.all([
      supabase.from('projects').select('id, status').eq('organization_id', orgId),
      supabase.from('sprints').select('id, status').eq('organization_id', orgId),
      supabase.from('tasks').select('id, status').eq('organization_id', orgId),
    ]);
    if (projRes.error) throw new Error(projRes.error.message);
    if (sprintRes.error) throw new Error(sprintRes.error.message);
    if (taskRes.error) throw new Error(taskRes.error.message);
    const projects = projRes.data || [];
    const sprints = sprintRes.data || [];
    const tasks = taskRes.data || [];
    const metrics = [
      { Metric: 'Total Projects', Value: projects.length },
      { Metric: 'Active Projects', Value: projects.filter((p) => p.status === 'ACTIVE').length },
      { Metric: 'Total Sprints', Value: sprints.length },
      { Metric: 'Total Tasks', Value: tasks.length },
      { Metric: 'Completed Tasks', Value: tasks.filter((t) => t.status === 'DONE').length },
    ];
    return { csv: toCsv(['Metric', 'Value'], metrics), rowCount: metrics.length };
  }

  if (report.type === 'PROJECT_HEALTH') {
    const { data, error } = await supabase
      .from('projects')
      .select('code, name, status, health, priority, security_classification, start_date, target_end_date')
      .eq('organization_id', orgId)
      .is('archived_at', null)
      .order('created_at', { ascending: false });
    if (error) throw new Error(error.message);
    const headers = ['code', 'name', 'status', 'health', 'priority', 'security_classification', 'start_date', 'target_end_date'];
    return { csv: toCsv(headers, data || []), rowCount: (data || []).length };
  }

  if (report.type === 'SPRINT_SUMMARY') {
    const { data, error } = await supabase
      .from('sprints')
      .select('name, goal, status, start_date, end_date, capacity_hours, planned_story_points, completed_story_points')
      .eq('organization_id', orgId)
      .order('start_date', { ascending: false });
    if (error) throw new Error(error.message);
    const headers = ['name', 'goal', 'status', 'start_date', 'end_date', 'capacity_hours', 'planned_story_points', 'completed_story_points'];
    return { csv: toCsv(headers, data || []), rowCount: (data || []).length };
  }

  throw new Error(`Unsupported report type for scheduled delivery: ${report.type}`);
}

// Local dev transport: Supabase's bundled Inbucket/Mailpit SMTP catcher.
// Requires `smtp_port` to be uncommented under [inbucket] in
// supabase/config.toml (and `supabase stop && supabase start` to apply it) —
// left commented by default so this worker doesn't force a stack restart.
// In production, point this at a real provider (Resend/Postmark) via env vars
// instead: SMTP_HOST/SMTP_PORT/SMTP_USER/SMTP_PASS, or swap nodemailer for
// the provider's SDK.
function buildTransport() {
  const host = process.env.SMTP_HOST || '127.0.0.1';
  const port = Number(process.env.SMTP_PORT || 54325);
  return nodemailer.createTransport({
    host,
    port,
    secure: false,
    ignoreTLS: true,
    auth: process.env.SMTP_USER ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } : undefined,
  });
}

async function sendReportEmail(report, recipients, csv, fileName) {
  const transport = buildTransport();
  await transport.sendMail({
    from: process.env.REPORTS_FROM_EMAIL || 'reports@handoff.local',
    to: recipients.join(', '),
    subject: `Scheduled report: ${report.name}`,
    text: `Your scheduled report "${report.name}" is attached.`,
    attachments: [{ filename: fileName, content: csv, contentType: 'text/csv' }],
  });
}

/** Optimistic-lock claim: only succeeds if next_run_at still matches what we
 * read (i.e. no other worker has claimed it since). Pushes next_run_at
 * forward by LOCK_TTL_MS as the "in progress" marker. */
async function claimSchedule(schedule) {
  const { data, error } = await supabase
    .from('report_schedules')
    .update({ next_run_at: new Date(Date.now() + LOCK_TTL_MS).toISOString(), updated_at: new Date().toISOString() })
    .eq('id', schedule.id)
    .eq('next_run_at', schedule.next_run_at)
    .select('id');
  if (error) {
    console.error(`[Worker] Claim failed for ${schedule.id}:`, error.message);
    return false;
  }
  return (data || []).length === 1;
}

function computeNextRun(cronExpression) {
  try {
    const interval = cronParser.parseExpression(cronExpression, { currentDate: new Date() });
    return interval.next().toDate();
  } catch (err) {
    console.error(`[Worker] Invalid cron_expression "${cronExpression}", falling back to +1 day:`, err.message);
    const fallback = new Date();
    fallback.setDate(fallback.getDate() + 1);
    return fallback;
  }
}

async function processSchedule(schedule) {
  const claimed = await claimSchedule(schedule);
  if (!claimed) {
    console.log(`[Worker] Schedule ${schedule.id} already claimed by another worker, skipping.`);
    return;
  }

  let status = 'FAILED';
  try {
    const { data: report, error: reportError } = await supabase
      .from('reports')
      .select('id, organization_id, name, type')
      .eq('id', schedule.report_id)
      .single();
    if (reportError || !report) throw new Error(reportError?.message || 'Report not found');

    const { csv, rowCount } = await generateReportCsv(report);
    const fileName = `${report.name.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-${Date.now()}.csv`;

    if (!schedule.recipients || schedule.recipients.length === 0) {
      throw new Error('No recipients configured');
    }
    await sendReportEmail(report, schedule.recipients, csv, fileName);

    status = 'DELIVERED';
    console.log(`[Worker] Schedule ${schedule.id} delivered (${rowCount} rows) to ${schedule.recipients.join(', ')}.`);
  } catch (err) {
    console.error(`[Worker] Schedule ${schedule.id} failed:`, err.message);
  }

  await supabase.from('report_deliveries').insert({ schedule_id: schedule.id, status });

  // Now that processing is done, set the real next_run_at (overwrites the
  // temporary lock-TTL value set by claimSchedule).
  const nextRun = computeNextRun(schedule.cron_expression);
  await supabase
    .from('report_schedules')
    .update({ next_run_at: nextRun.toISOString(), updated_at: new Date().toISOString() })
    .eq('id', schedule.id);

  console.log(`[Worker] Schedule ${schedule.id} next run: ${nextRun.toISOString()}`);
}

async function pollSchedules() {
  console.log('[Worker] Polling for due report schedules...');

  const { data: schedules, error } = await supabase
    .from('report_schedules')
    .select('id, report_id, cron_expression, recipients, next_run_at')
    .lte('next_run_at', new Date().toISOString());

  if (error) {
    console.error('[Worker] Error fetching schedules:', error.message);
    return;
  }

  for (const schedule of schedules || []) {
    await processSchedule(schedule);
  }
}

console.log('Starting local dev report worker. Polling every 30s...');
setInterval(pollSchedules, 30 * 1000);
pollSchedules(); // run once immediately
